---
- name: Get label vars
  shell: gcloud compute instances list --filter="name:$(hostname)" --format 'json(labels)' | jq .[].labels
  register: instance_labels

- debug:
    msg: "{{instance_labels}}"