---
- name: Expose instance labels as instance_labels var
  include: label-vars.yml

- pip:
    executable: /usr/local/bin/pip
    name:
      - docker-compose
      - requests
      - polling

- name: App directory exists
  file:
    path: "{{ docker_service_app_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_service_user }}"

- name: Docker deamon is running
  service:
    name: docker
    state: started

- name: gcloud Docker auth configured
  shell: gcloud auth configure-docker
  become_user: "{{ docker_service_user }}"

- name: Cron script exists
  template:
    src: check_config.py.j2
    dest: /usr/local/bin/check_config.py
    owner: "{{ docker_service_user }}"
    mode: '0755'

- name: Cron job logging directory exists
  file:
    path: "/var/log/{{ instance_labels.app }}"
    state: directory
    mode: '0755'  
    owner: "{{ docker_service_user }}"

- name: Set up cron job to monitor config
  cron:
    name: "check {{ instance_labels.app }} config"
    job: "python3.6 /usr/local/bin/check_config.py >> /var/log/{{ instance_labels.app }}/{{ instance_labels.app }}_config.log 2>&1"
