---
- pip:
    executable: /usr/local/bin/pip
    name: docker-compose

- name: Create app directory if it does not exist
  file:
    path: "{{ docker_service_app_directory }}"
    state: directory
    mode: '0755'
  become_user: "{{ docker_service_user }}"

- name: Download config files
  shell: gsutil rsync -r gs://{{ docker_service_owner }}-{{ docker_service_name }}-config {{ docker_service_app_directory }}
  become_user: "{{ docker_service_user }}"

- name: Configure gcloud Docker auth
  shell: gcloud auth configure-docker
  become_user: "{{ docker_service_user }}"

- name: Docker-compose
  shell: /usr/local/bin/docker-compose -f /app/docker-compose.yaml up
  become_user: "{{ docker_service_user }}"
