---
- name: Create app directory if it does not exist
  file:
    path: "{{ docker_service_app_directory }}"
    state: directory
    mode: '0755'

- name: Download config files
  shell: gsutil rsync -r gs://{{ docker_service_owner }}-{{ docker_service_name }}-config {{ docker_service_app_directory }}

- name: Configure gcloud Docker auth
  shell: gcloud auth configure-docker

- name: Docker-compose
  shell: docker-compose -f /app/docker-compose.yaml
