---
- name: Expose instance labels as instance_labels var
  include: label-vars.yml

- name: Setup config virtualenv
  pip:
    virtualenv_python: python3.6
    virtualenv_command: /usr/local/bin/virtualenv
    virtualenv: "/home/{{ docker_service_user }}/.virtualenvs/config"
    virtualenv_site_packages: yes
    name:
      - docker-compose
      - polling
  become: yes
  become_user: "{{ docker_service_user }}"

- name: App directory exists
  file:
    path: "{{ docker_service_app_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_service_user }}"
    group: "{{ docker_service_user }}"

- name: Docker deamon is running
  service:
    name: docker
    state: started

- name: gcloud Docker auth configured
  shell: gcloud auth configure-docker
  args:
    creates: "/home/{{ docker_service_user }}/.docker/config.json"
  become: yes
  become_user: "{{ docker_service_user }}"

- name: Cron script exists
  template:
    src: check_config.py.j2
    dest: /usr/local/bin/check_config.py
    owner: "{{ docker_service_user }}"
    group: "{{ docker_service_user }}"
    mode: '0755'

- name: Cron job logging directory exists
  file:
    path: "/var/log/{{ instance_labels.app }}"
    state: directory
    mode: '0755'
    owner: "{{ docker_service_user }}"

- name: Config update cron job exists
  cron:
    name: "check {{ instance_labels.app }} config"
    job: "/home/{{ docker_service_user }}/.virtualenvs/config/bin/python3 /usr/local/bin/check_config.py 2>&1 | /usr/bin/logger -t {{ instance_labels.app }}_config"
    user: "{{ docker_service_user }}"
